/********************************************
ファイルパスを\で区切った場合
*********************************************/
deletefile   "c:\\temp\\test_w_en.ini";
//何故かファイル先頭に改行が挿入される
writeinistrw "c:\\temp\\test_w_en.ini", "foo", "bar" , "ひらがな";


deletefile   "c:\\temp\\test_en.ini";
//問題なし
writeinistr  "c:\\temp\\test_en.ini", "foo", "bar" , "ひらがな";


/********************************************
ファイルパスを/で区切った場合
*********************************************/
deletefile   "c:/temp/test_w_sl.ini";
//何故かshift-jisでファイルが生成される。
writeinistrw "c:/temp/test_w_sl.ini", "foo", "bar" , "ひらがな";

deletefile   "c:/temp/test_sl.ini";
//問題なし
writeinistr  "c:/temp/test_sl.ini", "foo", "bar" , "ひらがな";
